version: 2.1

orbs:
  node: 'circleci/node:4.1'

jobs:
  Base:
    executor:
      name: node/default
    steps:
      - name: Install dependencies
        run: yarn install --nonInteractive --frozen-lockfile --prefer-offline
      # - persist_to_workspace:
      #   # Must be an absolute path, or relative path from working_directory. This is a directory on the container which is
      #   # taken to be the root directory of the workspace.
      #   root: workspace
      #   # Must be relative path from root
      #   paths:
      #     - /

  Lint:
    executor:
      name: node/default
    steps:
      # - attach_workspace:
      #   # Must be absolute path or relative path from working_directory
      #   at: /
      - name: Lint
        run: yarn lint
      - name: Styling format check
        run: yarn format:check
  Coingecko:
    executor:
      name: node/default
    steps:
      # - attach_workspace:
      #   # Must be absolute path or relative path from working_directory
      #   at: /
      - name: Build
        run: lerna run build --scope @defiwrapper/coingecko
      - name: Test
        run: lerna run test --scope @defiwrapper/coingecko

# Invoke jobs via workflows
# See: https://circleci.com/docs/2.0/configuration-reference/#workflows
workflows:
  ci-workflow:
    jobs:
      - Base
      - Lint:
        requires:
          - Base
      - Coingecko:
        requires:
          - Base
