name: CI
on:
  push:
    branches:
      - main
  pull_request:

jobs:
  Lint:
    runs-on: ubuntu-latest
    timeout-minutes: 60
    env:
      CI: false
    steps:
      - uses: ./.github/workflows/base
      - name: Checkout repository
        uses: actions/checkout@v2
      - name: Lint
        run: yarn lint
      - name: Styling format check
        run: yarn format:check
  Coingecko:
    runs-on: ubuntu-latest
    timeout-minutes: 60
    env:
      CI: false
    steps:
      - uses: ./.github/workflows/base
      - name: Checkout repository
        uses: actions/checkout@v2
      - name: Build
        run: lerna run build --scope @defiwrapper/coingecko
      - uses: actions/upload-artifact@v3
        with:
          name: coingecko-build-artifact
          path: ./packages/coingecko/build
      - name: Test
        run: lerna run test --scope @defiwrapper/coingecko
  # TokenResolvers:
  #   runs-on: ubuntu-latest
  #   timeout-minutes: 60
  #   env:
  #     CI: false
  #   steps:
  #     - uses: ./.github/workflows/base
  #     - name: Checkout repository
  #       uses: actions/checkout@v2
  #     - name: Build
  #       run: lerna run build --scope @defiwrapper/token-resolvers
  #     - uses: actions/upload-artifact@v3
  #       with:
  #         name: token-resolvers-build-artifact
  #         path: ./packages/**/token-resolvers/**/build
  #     - name: Test
  #       run: lerna run test --scope @defiwrapper/token-resolvers
  # AccountResolvers:
  #   needs:
  #     - TokenResolvers
  #   runs-on: ubuntu-latest
  #   timeout-minutes: 60
  #   env:
  #     CI: false
  #   steps:
  #     - uses: ./.github/workflows/base
  #     - name: Checkout repository
  #       uses: actions/checkout@v2
  #     - name: Build
  #       run: lerna run build --scope @defiwrapper/account-resolvers
  #     - name: Test
  #       run: lerna run test --scope @defiwrapper/account-resolvers
  # PriceResolvers:
  #   needs:
  #     - Base
  #     - TokenResolvers
  #     - Coingecko
  #   runs-on: ubuntu-latest
  #   timeout-minutes: 60
  #   env:
  #     CI: false
  #   steps:
  #     - name: Checkout repository
  #       uses: actions/checkout@v2
  #     - name: Build
  #       run: lerna run build --scope @defiwrapper/price-resolvers
  #     - name: Test
  #       run: lerna run test --scope @defiwrapper/price-resolvers
  # ProtocolResolvers:
  #   needs:
  #     - Base
  #     - TokenResolvers
  #   runs-on: ubuntu-latest
  #   timeout-minutes: 60
  #   env:
  #     CI: false
  #   steps:
  #     - name: Checkout repository
  #       uses: actions/checkout@v2
  #     - name: Build
  #       run: lerna run build --scope @defiwrapper/protocol-resolvers
  #     - name: Test
  #       run: lerna run test --scope @defiwrapper/protocol-resolvers
  # AssetResolvers:
  #   needs:
  #     - Base
  #     - TokenResolvers
  #   runs-on: ubuntu-latest
  #   timeout-minutes: 60
  #   env:
  #     CI: false
  #   steps:
  #     - name: Checkout repository
  #       uses: actions/checkout@v2
  #     - name: Build
  #       run: lerna run build --scope @defiwrapper/asset-resolvers
  #     - name: Test
  #       run: lerna run test --scope @defiwrapper/asset-resolvers
  # CoreSDK:
  #   needs:
  #     - Base
  #     - TokenResolvers
  #     - PriceResolvers
  #     - AssetResolvers
  #     - ProtocolResolvers
  #     - AccountResolvers
  #   runs-on: ubuntu-latest
  #   timeout-minutes: 60
  #   env:
  #     CI: false
  #   steps:
  #     - name: Checkout repository
  #       uses: actions/checkout@v2
  #     - name: Build
  #       run: lerna run build --scope @defiwrapper/core-sdk-interface && lerna run build --scope @defiwrapper/core-sdk
  #     - name: Test
  #       run: lerna run test --scope @defiwrapper/core-sdk
